# Generated by Django 4.1.3 on 2022-11-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="post", through="news.PostCategory", to="news.category"
            ),
        ),
    ]
